export const CHANNELS_REQUEST = "CHANNELS_REQUEST";
export const CHANNELS_SUCCESS = "CHANNELS_SUCCESS";
export const CHANNELS_FAIL = "CHANNELS_FAIL";

export const MULTISELECT_CHANNEL_LIST = "MULTISELECT_CHANNEL_LIST";

export const CHANNELPOSTS_REQUEST = "CHANNELPOSTS_REQUEST";
export const CHANNELPOSTS_SUCCESS = "CHANNELPOSTS_SUCCESS";
export const CHANNELPOSTS_FAIL = "CHANNELPOSTS_FAIL";
